version: '3'

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    #    we are linking then here because web is depending from db
    links:
      - db
  web2:
    build: ./textSimilarity
    ports:
      - "5010:5010"
    #    we are linking then here because web is depending from db
    links:
      - db
  db:
    build: ./db
